name: CheckFormat
on:
  pull_request:
    branches: [master]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: |
          npm ci

  prettier:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: CheckPrettier
        run: |
          npm run test:prettier

  lintJS:
    runs-on: ubuntu-lastest
    needs: setup
    steps:
      - name: CheckJS
        run: |
          npm run test:js

  lintCSS:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: CheckCSS
        run: |
          npm run test:css
