name: Format
on:
  push:
    branches: [master]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: |
          npm ci

  prettier:
    needs: setup
    steps:
      - name: Prettier
      - run: |
          npm run prettier
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}

  lintJS:
    needs: setup
    steps:
      - name: CheckJS
        run: |
          npm run test:js

  lintCSS:
    needs: setup
    steps:
      - name: CheckCSS
        run: |
          npm run test:css
